/*delete from regýons;
delete from countrýes;

COMMIT ;


SELECT*FROM regýons;*/

SELECT * FROM employees
//
SELECT MANAGER_ID,FIRST_NAME,LAST_NAME,EMAIL FROM employees;
//
SELECT MANAGER_ID MGR,FIRST_NAME AD,LAST_NAME SOYAD,EMAIL POSTA FROM employees;
//
SELECT MANAGER_ID "MUDURNO",FIRST_NAME "ILK AD",LAST_NAME "SON AD",EMAIL "POSTA" FROM employees;
//
SELECT*FROM employees where DEPARTMENT_ID=90;
//
SELECT*FROM employees where DEPARTMENT_ID=100;
//
SELECT*FROM employees where DEPARTMENT_ID IN(90,100);
SELECT*FROM employees where DEPARTMENT_ID=90 OR DEPARTMENT_ID=100;
//
SELECT*FROM employees WHERE LAST_NAME LIKE 'M%';
//
SELECT*FROM employees WHERE LAST_NAME LIKE '%ma%';
//
SELECT * FROM employees where LAST_NAME like '_a_e%';
//
SELECT * FROM employees where salary>10000 and COMMISSION_PCT IS NOT NULL;
//

SELECT * FROM employees order by DEPARTMENT_ID DESC SALARY ASC,JOB_ID;
//
SELECT MANAGER_ID,FIRST_NAME,LAST_NAME,EMAIL FROM employees
ORDER BY 2 ASC,3 DESC ;
//ASC ARTAN DESC AZALAN
//
SELECT*FROM employees where DEPARTMENT_ID=100 ORDER BY SALARY DESC;