SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM employees
CONNECT BY PRIOR employee_ýd=manager_ýd
//
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM employees
CONNECT BY  employee_ýd= PRIOR manager_ýd//
//3

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID ,LEVEL 
FROM employees
START WITH EMPLOYEE_ID=100
CONNECT BY PRIOR employee_ýd=manager_ýd;



SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID ,LEVEL 
FROM employees
START WITH EMPLOYEE_ID=100
CONNECT BY PRIOR employee_ýd=manager_ýd
ORDER   SIBLINGS BY LAST_NAME;


SELECT LAST_NAME,LEVEL-1,SYS_CONNECT_BY_PATH(LAST_NAME,'->')
FROM EMPLOYEES 
CONNECT BY PRIOR EMPLOYEE_ID=MANAGER_ID;


SELECT LAST_NAME,LEVEL-1,SYS_CONNECT_BY_PATH(LAST_NAME,'-/')
FROM EMPLOYEES 
CONNECT BY PRIOR EMPLOYEE_ID=MANAGER_ID;


SELECT LAST_NAME,CONNECT_BY_ROOT LAST_NAME,
LEVEL-1,SYS_CONNECT_BY_PATH(LAST_NAME,'->')
FROM EMPLOYEES 
CONNECT BY PRIOR EMPLOYEE_ID=MANAGER_ID;




SELECT LAST_NAME calisan,CONNECT_BY_ROOT LAST_NAME yonetici,
LEVEL-1 seviye,SYS_CONNECT_BY_PATH(LAST_NAME,'->') path
FROM EMPLOYEES 
where DEPARTMENT_ID=110 AND LEVEL>1
CONNECT BY PRIOR EMPLOYEE_ID=MANAGER_ID;
