SELECT department_name ,LOWER (department_name)  FROM departments;
--lower küçük
SELECT department_name ,LOWER (department_name),UPPER(department_name)  FROM departments;
--upper büyük

SELECT department_name ,LOWER (department_name),UPPER(department_name),INITCAP(LOWER(department_name)) FROM departments;
--ýnýtcap ilk harfi büyüj
SELECT department_name ,LOWER (department_name),UPPER(department_name),INITCAP(LOWER(department_name)),SUBSTR(department_name,1,5) FROM departments;

--SUBSTACT 1,5 KISMINI GÖSTERÝR
-- harf uzunluðu
SELECT department_name ,LOWER (department_name),UPPER(department_name),INITCAP(LOWER(department_name)),SUBSTR(department_name,4),LENGTH(department_name) FROM departments;
--
SELECT INSTR('AYHAN CELÝK','N'),INSTR('AYHAN CELÝK','N',1,1),INSTR('AYHAN CELÝK','B',4.1)FROM DUAL;

--REPLACEK
SELECT REPLACE ('AYHAN CELÝK','AYHAN','A'),REPLACE ('AYHAN CELÝK','H','X'),REPLACE ('AYHAN CELÝK','K','\')from dual;

SELECT FIRST_NAME,JOB_ID,REPLACE(JOB_ID,'IT','BT'),REPLACE(JOB_ID,'IT','BIL') FROM EMPLOYEES WHERE JOB_ID LIKE '%IT%';

--TRANSLATE
SELECT TRANSLATE ('Oracle SQL','r0aScl','123456')from dual;
-- her harf kendsinden sonra harfle deðiþir
SELECT 'AYHAN ÇELÝK MERHABA'ORJ_MESAJ, TRANSLATE('AYHAN ÇELÝK MERHABA','ADADGASDGHADHJAGDAHDGHJA','ADADGASDGHADHJAGDAHDGHJA') SÝFRELÝMESAJ FROM DUAL;



SELECT 'AYHAN ÇELÝK MERHABA'ORJ_MESAJ, TRANSLATE('AYHAN ÇELÝK MERHABA','ADADGASDGHADHJAGDAHDGHJA','ADADGASDGHADHJAGDAHDGHJA') SÝFRELÝMESAJ FROM DUAL;

--RDAP

SELECT*FROM EMPLOYEES;


SELECT LAST_NAME,RPAD(LAST_NAME,30,'*'),
LPAD(LAST_NAME,30,'/')
FROM EMPLOYEES;




---LTRIM SOL TARAFTAKÝ BOÞLUKLARI TEMÝZLER

SELECT LTRIM('             Oracle Sql              ')from dual;


--rtrým
SELECT LTRIM('             Oracle Sql              ')
, RTRIM('             Oracle Sql              ')from dual;

--CONCAT BÝRLEÞTRÝME
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME,LAST_NAME) FROM EMPLOYEES;



SELECT CONCAT(CONCAT (FIRST_NAME,''),LAST_NAME) FROM EMPLOYEES;


SELECT FIRST_NAME ||''||LAST_NAME,CONCAT(CONCAT(FIRST_NAME,''),LAST_NAME)FROM employees;


SELECT CONCAT(CONCAT (FIRST_NAME,'Is a'),JOB_ID)FROM EMPLOYEES;


SELECT FIRST_NAME || 'Is a '||JOB_ID,CONCAT(CONCAT(FIRST_NAME,'Is a'),JOB_ID)FROM EMPLOYEES;


---NVL(A,B)

SELECT FIRST_NAME,COMMISSION_PCT FROM EMPLOYEES;

SELECT FIRST_NAME,COMMISSION_PCT, NVL(COMMISSION_PCT,0),NVL(COMMISSION_PCT,'bos') FROM EMPLOYEES;


--nvl2(p1,p2,p3)
SELECT FIRST_NAME,SALARY,COMMISSION_PCT,NVL2(COMMISSION_PCT,SALARY*(1+COMMISSION_PCT),SALARY) FROM EMPLOYEES;



--NULLIF
SELECT FIRST_NAME,SALARY,COMMISSION_PCT, NULLIF(SALARY,SALARY-NVL(COMMISSION_PCT,0)) FROM EMPLOYEES;


--GREATEST
SELECT GREATEST(1,2,3,-2,100,-500,5,3,2),GREATEST('AYHAN','CELIK','Z')FROM DUAL;


--DECODE
SELECT LAST_NAME ,DEPARTMENT_ID, DECODE(DEPARTMENT_ID,10,'Muhasebe',20,'Araþtýrma',30,'Satýs',40,'BT',50,'Diger') FROM EMPLOYEES ORDER BY 2;

--CASE
SELECT LAST_NAME ,DEPARTMENT_ID,case DEPARTMENT_ID WHEN 10 THEN'Muhasebe'
when 20 then 'araþtýrma'
when 30 then 'satýs'
when 40 then 'insan kaynaklarý'
when 50 then 'BT'
else 'diger'
end as DEPARTMENT
FROM EMPLOYEES ORDER BY 2;



--UND
SELECT UID, USER FROM DUAL;
SHOW USER;


--SYS_CONTEXT
SELECT SYS_CONTEXT ('USERENV','SESSION_USER')AS USERNAME,SYS_CONTEXT ('USERENC','ISDBA')ISDBA,SYS_CONTEXT('USERENV','HOST')HOST,SYS_CONTEXT ('USERENC','INSTANCE')INSTANCE,SYS_CONTEXT ('USERENC','IP_ADDRESS')IP,SYS_CONTEXT ('USERENC','DB_NAME')DBNAME
FROM DUAL;


--MAX,COUNT MIN AVAGRE 
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2),MAX(SALARY),MIN(SALARY),SUM(SALARY),COUNT(SALARY),ROUND(STDDEV(SALARY),2),ROUND(VARIANCE(SALARY),2)FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(SALARY)>1 ORDER BY DEPARTMENT_ID;
-- ANALÝTÝK 

SELECT FIRST_NAME,SALARY,SUM(SALARY) OVER (ORDER BY FIRST_NAME)AS toplammaas
from employees;


select FIRST_NAME,SALARY,DEPARTMENT_ID,
MAX(SALARY)OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY) AS SUMTOTOAL
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ;

---DATE
SELECT CURRENT_DATE,SYSDATE FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

ALTER SESSION SET TIME_ZONE='+2:0';

SELECT SYSTIMESTAMP FROM DUAL;

--DATE FROMATLARI
SELECT SYSDATE,
TO_CHAR(SYSDATE,'D')haftanýnkaçýncýgünü,
TO_CHAR(SYSDATE,'DD')ayýnkaçýncýgünü,
TO_CHAR(SYSDATE,'DDD')Yýlýnkaçýncýgünü,
TO_CHAR(SYSDATE,'DAY')günismi,
TO_CHAR(SYSDATE,'Dy')günkisaismi,
TO_CHAR(SYSDATE,'w')acinkacincihaftasý,
TO_CHAR(SYSDATE,'ww')yilinkacincihaftasi,
TO_CHAR(SYSDATE,'mm')ayno,
TO_CHAR(SYSDATE,'MON')ayismi,
TO_CHAR(SYSDATE,'YYYY')yil,
TO_CHAR(SYSDATE,'YEAR')yil,
TO_CHAR(SYSDATE,'HH24:MI:SS')saatdakika,
TO_CHAR(SYSDATE,'dd/mm/yyyy HH24:MI:SS')yil
from DUAL;









