CREATE TYPE ADRES_T AS OBJECT(
CADDE VARCHAR2(30),
SEHIR VARCHAR2(50),
ULKE_KODU CHAR(2),
POSTA_KODU CHAR(5)
);  

CREATE TYPE adres_tab ýs TABLE OF ADRES_T;


INSERT INTO MUSTERILER  VALUES (1,adres_tab(ADRES_T('ÝSTANBUL CAD','ANKARA','TR','06100'),
ADRES_T('BEYOGLU CAD','ÝSTANBUL','TR','34100')
)
);

INSERT INTO MUSTERILER  VALUES (2,adres_tab(ADRES_T('ÝSTANBUL CAD','ANKARA','TR','06100'),
ADRES_T('BAGDAT CAD','ÝSTANBUL','TR','34100')
)
);


SELECT 
m.musterý_ýd,u.*
from musterýler m,table(adres) u;
