CREATE TABLE MUSTERILER(
MUSTERI_ID NUMBER(10),
CADDE VARCHAR2(30),
SEHIR VARCHAR2(50),
ULKE_KODU CHAR(2),
POSTA_KODU CHAR(5),
)
CREATE TABLE MUSTERILER(
MUSTERI_ID NUMBER(10),
ADRES adres_tab
)
nested table ADRES STORE AS MUSTERI_ADRES;


DESC MUSTERILER;