/*SELECT TABLE_NAME FROM TABS;
--OBJECT PRÝVALEGES
GRANT SELECT ON REGIONS TO CELIK;

GRANT INSERT ON REGIONS TO CELIK;
GRANT UPDATE,DELETE ON REGIONS TO CELIK WITH GRANT OPTION;*/


//SELECT*FROM user_tab_prývs_made;

/*REVOKE SELECT ON REGIONS FROM CELIK;
REVOKE DELETE,UPDATE ON REGIONS FROM CELIK;

GRANT SELECT ON REGIONS TO PUBLIC;


REVOKE INSERT ON REGIONS FROM CELIK;*/


--ROLES
/*CREATE ROLE R_SELUPT;

CREATE ROLE R_INSDEL;
GRANT SELECT,UPDATE ON REGIONS TO R_SELUPT;

GRANT INSERT,DELETE ON REGIONS TO R_INSDEL;

GRANT R_SELUPT TO BILGE;
GRANT R_INSDEL TO CELIK;

REVOKE UPDATE ON REGIONS FROM R_SELUPT;


REVOKE R_INSDEL FROM CELIK;
DROP ROLE R_INSDEL;*/