/*SELECT *FROM AYHAN.REGIONS;

INSERT INTO AYHAN.REGIONS(REGION_ID,REGION_NAME)VALUES(6,'Antarika');

DELETE FROM AYHAN.REGIONS WHERE REGION_ID=6;
GRANT UPDATE ,DELETE ON REGIONS TO AYHAN

COMMÝT;*/


SET ROLE R_INSDEL;
INSERT INTO AYHAN.regýons VALUES(7,'ABC');
COMMIT;